name: 'Prepare Webdriver'
runs:
  using: "composite"
  steps:
    - name: Install Webdriver version
      run: |
        ./node_modules/.bin/webdriver-manager update --gecko=false
        ./node_modules/protractor/bin/webdriver-manager update --gecko=false
      shell: bash
