//
//  Design setup for the pure design
//
//   Copyright (C) 2012 by Christian Mayer
//   cometvisu (at) ChristianMayer.de
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program; if not, write to the
//   Free Software Foundation, Inc.,
//   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
//////////////////////////////////////////////////////////////////////////////

icons.insert({
  'audio_audio'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_audio.png' } } },
  'audio_eject'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_eject.png' } } },
  'audio_ff'              : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_ff.png' } } },
  'audio_mute'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_mute.png' } } },
  'audio_pause'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_pause.png' } } },
  'audio_playliste'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_playliste.png' } } },
  'audio_play'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_play.png' } } },
  'audio_rec'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_rec.png' } } },
  'audio_rew'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_rew.png' } } },
  'audio_sound'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_sound.png' } } },
  'audio_stop'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/audio_stop.png' } } },
  'fts_fenster_gekippt'   : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_fenster_gekippt.png' } } },
  'fts_fenster_offen'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_fenster_offen.png' } } },
  'fts_fenster'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_fenster.png' } } },
  'fts_garage'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_garage.png' } } },
  'fts_markise'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_markise.png' } } },
  'fts_rollo'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_rollo.png' } } },
  'fts_tuer_offen'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_tuer_offen.png' } } },
  'fts_tuer'              : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/fts_tuer.png' } } },
  'it_fernsehen'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_fernsehen.png' } } },
  'it_funk_dcf77'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_funk_dcf77.png' } } },
  'it_internet'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_internet.png' } } },
  'it_kamera'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_kamera.png' } } },
  'it_nas'                : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_nas.png' } } },
  'it_netz'               : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_netz.png' } } },
  'it_netzwerk'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_netzwerk.png' } } },
  'it_pc'                 : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_pc.png' } } },
  'it_radio'              : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_radio.png' } } },
  'it_router'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_router.png' } } },
  'it_server'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_server.png' } } },
  'it_smartphone'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_smartphone.png' } } },
  'it_telefon'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_telefon.png' } } },
  'it_wlan'               : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/it_wlan.png' } } },
  'licht_esstisch'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_esstisch.png' } } },
  'licht_indirekt'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_indirekt.png' } } },
  'licht_led'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_led.png' } } },
  'licht_lichterkette'    : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_lichterkette.png' } } },
  'licht_licht'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_licht.png' } } },
  'licht_party'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_party.png' } } },
  'licht_regelung'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_regelung.png' } } },
  'licht_stehlampe'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/licht_stehlampe.png' } } },
  'meld_achtung'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/meld_achtung.png' } } },
  'meld_medizin'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/meld_medizin.png' } } },
  'meld_post_offen'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/meld_post_offen.png' } } },
  'meld_post'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/meld_post.png' } } },
  'meld_service'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/meld_service.png' } } },
  'meld_steckdose'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/meld_steckdose.png' } } },
  'sani_bewaesserung'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_bewaesserung.png' } } },
  'sani_fussbodenheizung' : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_fussbodenheizung.png' } } },
  'sani_heizung'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_heizung.png' } } },
  'sani_kessel_temp'      : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_kessel_temp.png' } } },
  'sani_lueftung'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_lueftung.png' } } },
  'sani_lueftung_regelung': { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_lueftung_regelung.png' } } },
  'sani_pumpe'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_pumpe.png' } } },
  'sani_solar'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_solar.png' } } },
  'sani_solar_temp'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_solar_temp.png' } } },
  'sani_wasserhahn'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/sani_wasserhahn.png' } } },
  'secur_alarmanlage'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_alarmanlage.png' } } },
  'secur_codierung'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_codierung.png' } } },
  'secur_frostschutz'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_frostschutz.png' } } },
  'secur_hitzeschutz'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_hitzeschutz.png' } } },
  'secur_offen'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_offen.png' } } },
  'secur_rauchmelder'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_rauchmelder.png' } } },
  'secur_zu'              : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/secur_zu.png' } } },
  'steuer_ab'             : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_ab.png' } } },
  'steuer_alles_ein_aus'  : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_alles_ein_aus.png' } } },
  'steuer_auf'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_auf.png' } } },
  'steuer_aussen_ein_aus' : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_aussen_ein_aus.png' } } },
  'steuer_ein_aus'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_ein_aus.png' } } },
  'steuer_home'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_home.png' } } },
  'steuer_minus'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_minus.png' } } },
  'steuer_plus'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_plus.png' } } },
  'steuer_standby'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_standby.png' } } },
  'steuer_vor'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_vor.png' } } },
  'steuer_x'              : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_x.png' } } },
  'steuer_zurueck'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/steuer_zurueck.png' } } },
  'szene_essen'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_essen.png' } } },
  'szene_garten'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_garten.png' } } },
  'szene_kochen'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_kochen.png' } } },
  'szene_making_love'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_making_love.png' } } },
  'szene_nacht'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_nacht.png' } } },
  'szene_party'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_party.png' } } },
  'szene_pool'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_pool.png' } } },
  'szene_schlafen'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_schlafen.png' } } },
  'szene_schwimmen'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_schwimmen.png' } } },
  'szene_szene'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_szene.png' } } },
  'szene_terrasse'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_terrasse.png' } } },
  'szene_toilette'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_toilette.png' } } },
  'szene_weihnachten'     : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/szene_weihnachten.png' } } },
  'temp_aussen'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/temp_aussen.png' } } },
  'temp_frost'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/temp_frost.png' } } },
  'temp_innen'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/temp_innen.png' } } },
  'temp_regelung'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/temp_regelung.png' } } },
  'temp_temperatur'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/temp_temperatur.png' } } },
  'user_abwesend'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/user_abwesend.png' } } },
  'user_anwesend'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/user_anwesend.png' } } },
  'user_ext_away'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/user_ext_away.png' } } },
  'wetter_bewoelkt'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_bewoelkt.png' } } },
  'wetter_feuchtigkeit'   : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_feuchtigkeit.png' } } },
  'wetter_gewitter'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_gewitter.png' } } },
  'wetter_pollen'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_pollen.png' } } },
  'wetter_regen'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_regen.png' } } },
  'wetter_schnee'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_schnee.png' } } },
  'wetter_sommer'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_sommer.png' } } },
  'wetter_sonne'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_sonne.png' } } },
  'wetter_unwetter'       : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_unwetter.png' } } },
  'wetter_wind'           : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_wind.png' } } },
  'wetter_winter'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/wetter_winter.png' } } },
  'zeit_automatik'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_automatik.png' } } },
  'zeit_diagramm'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_diagramm.png' } } },
  'zeit_ecomode'          : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_ecomode.png' } } },
  'zeit_handbetrieb'      : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_handbetrieb.png' } } },
  'zeit_kalender'         : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_kalender.png' } } },
  'zeit_notiz'            : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_notiz.png' } } },
  'zeit_statistik'        : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_statistik.png' } } },
  'zeit_uhr'              : { '*': { '*': { 'uri': 'icon/knx-uf-iconset/128x128_ws/zeit_uhr.png' } } }
});