[cometvisu]
image=debian:bookworm
pull=true
init=false
root=false
start_now=true
# Basic utilities for terminal use
# Development packages
additional_packages="git libxml2-dev libxslt-dev"
# Python
additional_packages="python3 python3-pip python3-venv"
# JS
additional_packages="nodejs npm"
pre_init_hooks="export SHELL=/bin/bash"
init_hooks="python3 -m venv --system-site-packages .denv"
init_hooks="source .denv/bin/activate && pip install --upgrade pip"
init_hooks="pip install -r utils/requirements.txt"