[cometvisu]
image=debian:bookworm # python requirement lxml==4.9.4 does not compile with newer versions
pull=true
init=false
root=false
start_now=true
# Basic utilities for terminal use
# Development packages
additional_packages="git libxml2-dev libxslt-dev"
# Python
additional_packages="python3 python3-pip python-is-python3"
# JS
additional_packages="nodejs npm"
init_hooks="sudo pip install -r utils/requirements.txt --break-system-packages"