[cometvisu]
image=debian:bookworm # python requirement lxml==4.9.4 does not compile with newer versions
pull=true
init=false
root=false
start_now=true
# Basic utilities for terminal use
# Development packages
additional_packages="git vim vim-python-jedi"
# Python
additional_packages="libxml2-dev libxslt-dev python3 python3-pip python-is-python3"
# JS
additional_packages="nodejs npm grunt"
# For selenium (karma) support
additional_packages="libnspr4 libnss3 libatk-bridge2.0-0 libxkbcommon0 libasound2"
init_hooks="sudo pip install -r utils/requirements.txt --break-system-packages"

init_hooks="curl -sS https://starship.rs/install.sh | sh"

# Hints:
# Prepare test runs: 
# * npm run selenium (only needed once)
# * source .protractor-env (needed to run tests)