#!/usr/bin/env bash

cid=$(docker ps -a -f name=cv_doc --quiet)
if [[ ! -z "$cid" ]]; then
    docker rm $cid
fi
export COMMAND=$@
docker run --privileged --net=host -it -v "$(pwd)":"$(pwd)" -v /dev/shm:/dev/shm --name cv_doc --workdir "$(pwd)" -e COMMAND peuter/cv-doc-helper
