<?php
/**
 * EnvironmentState
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * EnvironmentState
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class EnvironmentState
{
    
    /** @var string $entity */
    private $entity;
    
    /** @var float $state bitmask with a list of states &lt;writeable,readable,exists&gt;*/
    private $state;
}
