<?php
/**
 * FsEntry
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * FsEntry
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class FsEntry
{
    
    /** @var string $name */
    private $name;
    
    /** @var string $type */
    private $type;
    
    /** @var string $parentFolder */
    private $parentFolder;
    
    /** @var bool $hasChildren */
    private $hasChildren;
    
    /** @var bool $readable */
    private $readable;
    
    /** @var bool $writeable */
    private $writeable;
    
    /** @var bool $mounted */
    private $mounted;
    
    /** @var bool $trash marks the trash folder*/
    private $trash;
    
    /** @var float $hash hash value for file content (CRC32)*/
    private $hash;
}
