<?php
/**
 * InlineObject
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * InlineObject
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class InlineObject
{
    
    /** @var \SplFileObject $file */
    private $file;
    
    /** @var string $filename filename to use (if it should be another one than the original filename)*/
    private $filename;
    
    /** @var bool $force replace existing file*/
    private $force;
}
