<?php
/**
 * ConfigApiTest
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * CometVisu Manager backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\ConfigApi;

/**
 * ConfigApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\ConfigApi
 */
class ConfigApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createHiddenConfig
     *
     * Creates a new config option.
     *
     * @covers ::createHiddenConfig
     */
    public function testCreateHiddenConfig()
    {
    }

    /**
     * Test case for deleteHiddenConfig
     *
     * Delete config option.
     *
     * @covers ::deleteHiddenConfig
     */
    public function testDeleteHiddenConfig()
    {
    }

    /**
     * Test case for getHiddenConfig
     *
     * Provides the value of a config option.
     *
     * @covers ::getHiddenConfig
     */
    public function testGetHiddenConfig()
    {
    }

    /**
     * Test case for saveHiddenConfig
     *
     * Save the hidden config.
     *
     * @covers ::saveHiddenConfig
     */
    public function testSaveHiddenConfig()
    {
    }

    /**
     * Test case for updateHiddenConfig
     *
     * Changes the value of an existing config option.
     *
     * @covers ::updateHiddenConfig
     */
    public function testUpdateHiddenConfig()
    {
    }
}
