<?php
/**
 * DataproviderApiTest
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * CometVisu Manager backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DataproviderApi;

/**
 * DataproviderApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DataproviderApi
 */
class DataproviderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAddresses
     *
     * Returns the list of available addresses..
     *
     * @covers ::getAddresses
     */
    public function testGetAddresses()
    {
    }

    /**
     * Test case for getDesigns
     *
     * Returns the list of available designs..
     *
     * @covers ::getDesigns
     */
    public function testGetDesigns()
    {
    }

    /**
     * Test case for getInfluxDBFields
     *
     * Returns the list of available influx database fields..
     *
     * @covers ::getInfluxDBFields
     */
    public function testGetInfluxDBFields()
    {
    }

    /**
     * Test case for getInfluxDBTags
     *
     * Returns the list of available influx database tags..
     *
     * @covers ::getInfluxDBTags
     */
    public function testGetInfluxDBTags()
    {
    }

    /**
     * Test case for getInfluxDBs
     *
     * Returns the list of available influx databases..
     *
     * @covers ::getInfluxDBs
     */
    public function testGetInfluxDBs()
    {
    }

    /**
     * Test case for getRRDs
     *
     * Returns the list of available RRDs..
     *
     * @covers ::getRRDs
     */
    public function testGetRRDs()
    {
    }
}
