<?php
/**
 * FsApiTest
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * CometVisu Manager backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\FsApi;

/**
 * FsApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\FsApi
 */
class FsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for checkEnvironment
     *
     * Check filesystem environment (access rights, etc).
     *
     * @covers ::checkEnvironment
     */
    public function testCheckEnvironment()
    {
    }

    /**
     * Test case for create
     *
     * Create a new file or folder on the host.
     *
     * @covers ::create
     */
    public function testCreate()
    {
    }

    /**
     * Test case for delete
     *
     * Deletes a file/folder.
     *
     * @covers ::delete
     */
    public function testDelete()
    {
    }

    /**
     * Test case for move
     *
     * Move folder or file to a new place.
     *
     * @covers ::move
     */
    public function testMove()
    {
    }

    /**
     * Test case for read
     *
     * Return directory listing or file content.
     *
     * @covers ::read
     */
    public function testRead()
    {
    }

    /**
     * Test case for update
     *
     * Update an existing file.
     *
     * @covers ::update
     */
    public function testUpdate()
    {
    }
}
