<?php
/**
 * FsEntryTest
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * CometVisu Manager backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\FsEntry;

/**
 * FsEntryTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\FsEntry
 */
class FsEntryTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FsEntry"
     */
    public function testFsEntry()
    {
        $testFsEntry = new FsEntry();
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "parentFolder"
     */
    public function testPropertyParentFolder()
    {
    }

    /**
     * Test attribute "hasChildren"
     */
    public function testPropertyHasChildren()
    {
    }

    /**
     * Test attribute "readable"
     */
    public function testPropertyReadable()
    {
    }

    /**
     * Test attribute "writeable"
     */
    public function testPropertyWriteable()
    {
    }

    /**
     * Test attribute "mounted"
     */
    public function testPropertyMounted()
    {
    }

    /**
     * Test attribute "trash"
     */
    public function testPropertyTrash()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }
}
