<?php
/**
 * AbstractFsApi
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * CometVisu Manager backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exception;

/**
 * AbstractFsApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractFsApi
{

    /**
     * @var ContainerInterface Slim app container instance
     */
    protected $container;

    /**
     * Route Controller constructor receives container
     *
     * @param ContainerInterface $container Slim app container instance
     */
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }


    /**
     * GET checkEnvironment
     * Summary: Check filesystem environment (access rights, etc)
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function checkEnvironment(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing checkEnvironment as a GET method in OpenAPIServer\Api\FsApi class?";
        throw new Exception($message);

        return $response->write($message)->withStatus(501);
    }

    /**
     * POST create
     * Summary: Create a new file or folder on the host
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function create(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $queryParams = $request->getQueryParams();
        $path = $request->getQueryParam('path');
        $hash = $request->getQueryParam('hash');
        $type = $request->getQueryParam('type');
        $file = (key_exists('file', $request->getUploadedFiles())) ? $request->getUploadedFiles()['file'] : null;
        $filename = $request->getParsedBodyParam('filename');
        $force = $request->getParsedBodyParam('force');
        $message = "How about implementing create as a POST method in OpenAPIServer\Api\FsApi class?";
        throw new Exception($message);

        return $response->write($message)->withStatus(501);
    }

    /**
     * DELETE delete
     * Summary: Deletes a file/folder
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function delete(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $queryParams = $request->getQueryParams();
        $path = $request->getQueryParam('path');
        $hash = $request->getQueryParam('hash');
        $force = $request->getQueryParam('force');
        $message = "How about implementing delete as a DELETE method in OpenAPIServer\Api\FsApi class?";
        throw new Exception($message);

        return $response->write($message)->withStatus(501);
    }

    /**
     * PUT move
     * Summary: Move folder or file to a new place
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function move(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $queryParams = $request->getQueryParams();
        $src = $request->getQueryParam('src');
        $target = $request->getQueryParam('target');
        $message = "How about implementing move as a PUT method in OpenAPIServer\Api\FsApi class?";
        throw new Exception($message);

        return $response->write($message)->withStatus(501);
    }

    /**
     * GET read
     * Summary: Return directory listing or file content
     * Notes: Returns a list of files/directories if the requested path pointed to a directory or the content of the file otherwise
     * Output-Formats: [application/json, text/_*]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function read(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $queryParams = $request->getQueryParams();
        $path = $request->getQueryParam('path');
        $hash = $request->getQueryParam('hash');
        $download = $request->getQueryParam('download');
        $recursive = $request->getQueryParam('recursive');
        $message = "How about implementing read as a GET method in OpenAPIServer\Api\FsApi class?";
        throw new Exception($message);

        return $response->write($message)->withStatus(501);
    }

    /**
     * PUT update
     * Summary: Update an existing file
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function update(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $queryParams = $request->getQueryParams();
        $path = $request->getQueryParam('path');
        $hash = $request->getQueryParam('hash');
        $body = $request->getParsedBody();
        $message = "How about implementing update as a PUT method in OpenAPIServer\Api\FsApi class?";
        throw new Exception($message);

        return $response->write($message)->withStatus(501);
    }
}
