name: Tag new pre-release
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Pre-release type'
        required: true
        default: 'rc'
        type: choice
        options:
          - alpha
          - beta
          - rc
jobs:
  tagger:
    runs-on: ubuntu-latest
    if: github.repository == 'CometVisu/CometVisu'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install action dependencies
        run: npm install
        working-directory: ./.github/actions/github
      - id: prerelease
        name: "Create tag on change"
        uses: ./.github/actions/github
        with:
          action: increase-build-tag
          options: "true ${{ inputs.type }}"
        env:
          COMMIT_AUTHOR_NAME: CometVisu-CI
          COMMIT_AUTHOR_EMAIL: generator@cometvisu.org
          NIGHLTY_ONLY: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger build
        uses: ./.github/actions/github
        with:
          action: trigger-build
          options: ${{ steps.prerelease.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }} # does not work with secrets.GITHUB_TOKEN, must be another token with rights for workflows
