name: Update coverage
on: 
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - 'source/**'
      - '!source/**/*.md'
      - '!source/**/*.html'
      - '!source/**/*.json'
      - '!source/**/*.xml'
      - '!source/**/*.yml'
      - '!source/**/*.yaml'
      - '!source/**/*.txt'
      - '!source/**/*.csv'
      - '!source/**/*.tsv'
env:
  NODE_VERSION: '24'
jobs:
  coveralls:
    name: "COVERALLS"
    runs-on: ubuntu-latest
    env:
      CV_VERSION: stable
      CV_BROWSER: Chrome_ci
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v5
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Build CometVisu
        uses: ./.github/actions/build-cv
        with:
          target: source
      - name: Install browser
        run: ./utils/ci/browser-setup.sh
        shell: bash
      - id: dotenv
        uses: falti/dotenv-action@v1.2.0
        with:
          path: .protractor-env
      - name: Run tests
        run: grunt karma:ci --browser=$CV_BROWSER
        env:
          CHROME_BIN: ${{ steps.dotenv.outputs.BROWSER_PATH }}
      - name: Run coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"